### PR TITLE
Update openssl 

### PR DESCRIPTION
**Pull request by poorndm**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Review by rahulgoel1 — COMMENTED** [review]
Chef infra client team has decided to use 3.0.11 which can be compiled for AIX and other esoteric platforms and eventually should work for other platforms.

**Comment by rahulgoel1** [comment]
@poorndm do you have updates as to when the changes will be available through chef-foundation ? This will enable our team to proceed with testing.

**Comment by poorndm** [comment]
> @poorndm do you have updates as to when the changes will be available through chef-foundation ? This will enable our team to proceed with testing.

@rahulgoel1  Sure will work on this and  keep you updated.
Please confirm if openssl - 3.0.x  is to be picked on AIX and esoteric platforms  and  3.1.x on other platforms ?

**Comment by muthuja** [comment]
i have opened a new pr with the same changes, since this one is opened long back ago , https://github.com/chef/chef-foundation/pull/102/files , we can track here

**Pull request closed without merging**
