### PR TITLE
openssl upgrade to 3.0.11

### PR DESCRIPTION
**Pull request by muthuja**
## Description
this changes will upgrade openssl version to 3.0.11 on all platforms,  except on aix . on aix it will be 1.0.2zi

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by rahulgoel1** [comment]
@anandhapadmanabhan  Would it be okay to merge this PR? We would like to proceed with testing openssl upgrade using CI pipeline so that issues are identified if any.

**Comment by muthuja** [comment]
> @anandhapadmanabhan Would it be okay to merge this PR? We would like to proceed with testing openssl upgrade using CI pipeline so that issues are identified if any.

@rahulgoel1  there is issue with AIX 7.1 builder https://buildkite.com/chef/chef-chef-foundation-main-omnibus-adhoc/builds/225#018cd036-3d59-4086-85e6-1ba5bf16cc4d/6-12695 so checking on it  , remaining all platforms build went through fine , will merge once this is fixed

**Comment by muthuja** [comment]
due to AIX build issue with 3.0.11 , i kept the old version of 1.0.2zi on aix and for rest of all platforms it will be 3.0.11

build log : https://buildkite.com/chef/chef-chef-foundation-main-omnibus-adhoc/builds/233#_

**Review by sean-simmons-progress — COMMENTED** [review]
lgtm. the build https://buildkite.com/chef/chef-chef-foundation-main-omnibus-adhoc/builds/233# was successful

**Review by sean-simmons-progress — APPROVED** [review]

**Pull request merged**
