### PR TITLE
Add RockyLinux-8 builder & Tester

### PR DESCRIPTION
**Pull request by poorndm**
A new platform called Rocky Linux has emerged out of CentOS. 
Add RockyLinux-8 Builder and tester

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by poorndm** [comment]
Ref Log : https://buildkite.com/chef/chef-chef-foundation-main-omnibus-adhoc/builds/77

**Review by sean-simmons-progress — APPROVED** [review]

**Review by sean-simmons-progress — CHANGES_REQUESTED** [review]
im looking into why aix is failing. we can merge once that passes.

**Comment by poorndm** [comment]
Test Log : https://buildkite.com/chef/chef-chef-foundation-main-omnibus-adhoc/builds/118#018a013b-4da6-42dd-a003-793ff2c143e8

**Review by muthuja — APPROVED** [review]

**Comment by poorndm** [comment]
> im looking into why aix is failing. we can merge once that passes.

Build had gone through fine on all platforms
https://buildkite.com/chef/chef-chef-foundation-main-omnibus-adhoc/builds/118 - Complete

**Review by anandhapadmanabhan — APPROVED** [review]

**Review by sean-simmons-progress — APPROVED** [review]

**Pull request merged**
